<script setup lang="ts">
import TicTacToe from './components/TicTacToe.vue';
</script>

<template>
  <div class="container">
    <h1>TicTacToe Demo</h1>
    <h3>These games have own isolated states generated by composable function.</h3>
    <div class="stack">
      <TicTacToe
        v-for="_ in 3"
      />
    </div>
  </div>
</template>

<style scoped>
.container {
  max-width: 800px;
  margin: auto;
}

.stack * + * {
  margin-top: 16px;
}
</style>